// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import CalendarTooltipsController from "./calendar_tooltips_controller"
application.register("calendar-tooltips", CalendarTooltipsController)

import DateFilterController from "./date_filter_controller"
application.register("date-filter", DateFilterController)

import EducatorsWizardController from "./educators_wizard_controller"
application.register("educators-wizard", EducatorsWizardController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import MultiFilterController from "./multi_filter_controller"
application.register("multi-filter", MultiFilterController)

import PageTitleController from "./page_title_controller"
application.register("page-title", PageTitleController)

import PressReleasesController from "./press_releases_controller"
application.register("press-releases", PressReleasesController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import StateFilterController from "./state_filter_controller"
application.register("state-filter", StateFilterController)

import VendorFilterController from "./vendor_filter_controller"
application.register("vendor-filter", VendorFilterController)
