require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/educators", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Educator. As you add validations to Educator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Educator.create! valid_attributes
      get educators_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      educator = Educator.create! valid_attributes
      get educator_url(educator)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_educator_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      educator = Educator.create! valid_attributes
      get edit_educator_url(educator)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Educator" do
        expect {
          post educators_url, params: { educator: valid_attributes }
        }.to change(Educator, :count).by(1)
      end

      it "redirects to the created educator" do
        post educators_url, params: { educator: valid_attributes }
        expect(response).to redirect_to(educator_url(Educator.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Educator" do
        expect {
          post educators_url, params: { educator: invalid_attributes }
        }.to change(Educator, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post educators_url, params: { educator: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested educator" do
        educator = Educator.create! valid_attributes
        patch educator_url(educator), params: { educator: new_attributes }
        educator.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the educator" do
        educator = Educator.create! valid_attributes
        patch educator_url(educator), params: { educator: new_attributes }
        educator.reload
        expect(response).to redirect_to(educator_url(educator))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        educator = Educator.create! valid_attributes
        patch educator_url(educator), params: { educator: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested educator" do
      educator = Educator.create! valid_attributes
      expect {
        delete educator_url(educator)
      }.to change(Educator, :count).by(-1)
    end

    it "redirects to the educators list" do
      educator = Educator.create! valid_attributes
      delete educator_url(educator)
      expect(response).to redirect_to(educators_url)
    end
  end
end
