require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/follow_ups", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FollowUp. As you add validations to FollowUp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FollowUp.create! valid_attributes
      get follow_ups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      follow_up = FollowUp.create! valid_attributes
      get follow_up_url(follow_up)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_follow_up_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      follow_up = FollowUp.create! valid_attributes
      get edit_follow_up_url(follow_up)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FollowUp" do
        expect {
          post follow_ups_url, params: { follow_up: valid_attributes }
        }.to change(FollowUp, :count).by(1)
      end

      it "redirects to the created follow_up" do
        post follow_ups_url, params: { follow_up: valid_attributes }
        expect(response).to redirect_to(follow_up_url(FollowUp.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FollowUp" do
        expect {
          post follow_ups_url, params: { follow_up: invalid_attributes }
        }.to change(FollowUp, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post follow_ups_url, params: { follow_up: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested follow_up" do
        follow_up = FollowUp.create! valid_attributes
        patch follow_up_url(follow_up), params: { follow_up: new_attributes }
        follow_up.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the follow_up" do
        follow_up = FollowUp.create! valid_attributes
        patch follow_up_url(follow_up), params: { follow_up: new_attributes }
        follow_up.reload
        expect(response).to redirect_to(follow_up_url(follow_up))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        follow_up = FollowUp.create! valid_attributes
        patch follow_up_url(follow_up), params: { follow_up: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested follow_up" do
      follow_up = FollowUp.create! valid_attributes
      expect {
        delete follow_up_url(follow_up)
      }.to change(FollowUp, :count).by(-1)
    end

    it "redirects to the follow_ups list" do
      follow_up = FollowUp.create! valid_attributes
      delete follow_up_url(follow_up)
      expect(response).to redirect_to(follow_ups_url)
    end
  end
end
