require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/na_teams", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # NaTeam. As you add validations to NaTeam, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      NaTeam.create! valid_attributes
      get na_teams_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      na_team = NaTeam.create! valid_attributes
      get na_team_url(na_team)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_na_team_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      na_team = NaTeam.create! valid_attributes
      get edit_na_team_url(na_team)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new NaTeam" do
        expect {
          post na_teams_url, params: { na_team: valid_attributes }
        }.to change(NaTeam, :count).by(1)
      end

      it "redirects to the created na_team" do
        post na_teams_url, params: { na_team: valid_attributes }
        expect(response).to redirect_to(na_team_url(NaTeam.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new NaTeam" do
        expect {
          post na_teams_url, params: { na_team: invalid_attributes }
        }.to change(NaTeam, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post na_teams_url, params: { na_team: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested na_team" do
        na_team = NaTeam.create! valid_attributes
        patch na_team_url(na_team), params: { na_team: new_attributes }
        na_team.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the na_team" do
        na_team = NaTeam.create! valid_attributes
        patch na_team_url(na_team), params: { na_team: new_attributes }
        na_team.reload
        expect(response).to redirect_to(na_team_url(na_team))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        na_team = NaTeam.create! valid_attributes
        patch na_team_url(na_team), params: { na_team: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested na_team" do
      na_team = NaTeam.create! valid_attributes
      expect {
        delete na_team_url(na_team)
      }.to change(NaTeam, :count).by(-1)
    end

    it "redirects to the na_teams list" do
      na_team = NaTeam.create! valid_attributes
      delete na_team_url(na_team)
      expect(response).to redirect_to(na_teams_url)
    end
  end
end
