require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/netball_academies", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # NetballAcademy. As you add validations to NetballAcademy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      NetballAcademy.create! valid_attributes
      get netball_academies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      netball_academy = NetballAcademy.create! valid_attributes
      get netball_academy_url(netball_academy)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_netball_academy_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      netball_academy = NetballAcademy.create! valid_attributes
      get edit_netball_academy_url(netball_academy)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new NetballAcademy" do
        expect {
          post netball_academies_url, params: { netball_academy: valid_attributes }
        }.to change(NetballAcademy, :count).by(1)
      end

      it "redirects to the created netball_academy" do
        post netball_academies_url, params: { netball_academy: valid_attributes }
        expect(response).to redirect_to(netball_academy_url(NetballAcademy.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new NetballAcademy" do
        expect {
          post netball_academies_url, params: { netball_academy: invalid_attributes }
        }.to change(NetballAcademy, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post netball_academies_url, params: { netball_academy: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested netball_academy" do
        netball_academy = NetballAcademy.create! valid_attributes
        patch netball_academy_url(netball_academy), params: { netball_academy: new_attributes }
        netball_academy.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the netball_academy" do
        netball_academy = NetballAcademy.create! valid_attributes
        patch netball_academy_url(netball_academy), params: { netball_academy: new_attributes }
        netball_academy.reload
        expect(response).to redirect_to(netball_academy_url(netball_academy))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        netball_academy = NetballAcademy.create! valid_attributes
        patch netball_academy_url(netball_academy), params: { netball_academy: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested netball_academy" do
      netball_academy = NetballAcademy.create! valid_attributes
      expect {
        delete netball_academy_url(netball_academy)
      }.to change(NetballAcademy, :count).by(-1)
    end

    it "redirects to the netball_academies list" do
      netball_academy = NetballAcademy.create! valid_attributes
      delete netball_academy_url(netball_academy)
      expect(response).to redirect_to(netball_academies_url)
    end
  end
end
