require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/netball_educators", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # NetballEducator. As you add validations to NetballEducator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      NetballEducator.create! valid_attributes
      get netball_educators_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      netball_educator = NetballEducator.create! valid_attributes
      get netball_educator_url(netball_educator)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_netball_educator_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      netball_educator = NetballEducator.create! valid_attributes
      get edit_netball_educator_url(netball_educator)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new NetballEducator" do
        expect {
          post netball_educators_url, params: { netball_educator: valid_attributes }
        }.to change(NetballEducator, :count).by(1)
      end

      it "redirects to the created netball_educator" do
        post netball_educators_url, params: { netball_educator: valid_attributes }
        expect(response).to redirect_to(netball_educator_url(NetballEducator.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new NetballEducator" do
        expect {
          post netball_educators_url, params: { netball_educator: invalid_attributes }
        }.to change(NetballEducator, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post netball_educators_url, params: { netball_educator: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested netball_educator" do
        netball_educator = NetballEducator.create! valid_attributes
        patch netball_educator_url(netball_educator), params: { netball_educator: new_attributes }
        netball_educator.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the netball_educator" do
        netball_educator = NetballEducator.create! valid_attributes
        patch netball_educator_url(netball_educator), params: { netball_educator: new_attributes }
        netball_educator.reload
        expect(response).to redirect_to(netball_educator_url(netball_educator))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        netball_educator = NetballEducator.create! valid_attributes
        patch netball_educator_url(netball_educator), params: { netball_educator: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested netball_educator" do
      netball_educator = NetballEducator.create! valid_attributes
      expect {
        delete netball_educator_url(netball_educator)
      }.to change(NetballEducator, :count).by(-1)
    end

    it "redirects to the netball_educators list" do
      netball_educator = NetballEducator.create! valid_attributes
      delete netball_educator_url(netball_educator)
      expect(response).to redirect_to(netball_educators_url)
    end
  end
end
