require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/open_invites", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # OpenInvite. As you add validations to OpenInvite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OpenInvite.create! valid_attributes
      get open_invites_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      open_invite = OpenInvite.create! valid_attributes
      get open_invite_url(open_invite)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_open_invite_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      open_invite = OpenInvite.create! valid_attributes
      get edit_open_invite_url(open_invite)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OpenInvite" do
        expect {
          post open_invites_url, params: { open_invite: valid_attributes }
        }.to change(OpenInvite, :count).by(1)
      end

      it "redirects to the created open_invite" do
        post open_invites_url, params: { open_invite: valid_attributes }
        expect(response).to redirect_to(open_invite_url(OpenInvite.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OpenInvite" do
        expect {
          post open_invites_url, params: { open_invite: invalid_attributes }
        }.to change(OpenInvite, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post open_invites_url, params: { open_invite: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested open_invite" do
        open_invite = OpenInvite.create! valid_attributes
        patch open_invite_url(open_invite), params: { open_invite: new_attributes }
        open_invite.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the open_invite" do
        open_invite = OpenInvite.create! valid_attributes
        patch open_invite_url(open_invite), params: { open_invite: new_attributes }
        open_invite.reload
        expect(response).to redirect_to(open_invite_url(open_invite))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        open_invite = OpenInvite.create! valid_attributes
        patch open_invite_url(open_invite), params: { open_invite: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested open_invite" do
      open_invite = OpenInvite.create! valid_attributes
      expect {
        delete open_invite_url(open_invite)
      }.to change(OpenInvite, :count).by(-1)
    end

    it "redirects to the open_invites list" do
      open_invite = OpenInvite.create! valid_attributes
      delete open_invite_url(open_invite)
      expect(response).to redirect_to(open_invites_url)
    end
  end
end
