require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/partners", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Partner. As you add validations to Partner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Partner.create! valid_attributes
      get partners_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      partner = Partner.create! valid_attributes
      get partner_url(partner)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_partner_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      partner = Partner.create! valid_attributes
      get edit_partner_url(partner)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Partner" do
        expect {
          post partners_url, params: { partner: valid_attributes }
        }.to change(Partner, :count).by(1)
      end

      it "redirects to the created partner" do
        post partners_url, params: { partner: valid_attributes }
        expect(response).to redirect_to(partner_url(Partner.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Partner" do
        expect {
          post partners_url, params: { partner: invalid_attributes }
        }.to change(Partner, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post partners_url, params: { partner: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested partner" do
        partner = Partner.create! valid_attributes
        patch partner_url(partner), params: { partner: new_attributes }
        partner.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the partner" do
        partner = Partner.create! valid_attributes
        patch partner_url(partner), params: { partner: new_attributes }
        partner.reload
        expect(response).to redirect_to(partner_url(partner))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        partner = Partner.create! valid_attributes
        patch partner_url(partner), params: { partner: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested partner" do
      partner = Partner.create! valid_attributes
      expect {
        delete partner_url(partner)
      }.to change(Partner, :count).by(-1)
    end

    it "redirects to the partners list" do
      partner = Partner.create! valid_attributes
      delete partner_url(partner)
      expect(response).to redirect_to(partners_url)
    end
  end
end
