require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sample_words", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SampleWord. As you add validations to SampleWord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SampleWord.create! valid_attributes
      get sample_words_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sample_word = SampleWord.create! valid_attributes
      get sample_word_url(sample_word)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sample_word_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sample_word = SampleWord.create! valid_attributes
      get edit_sample_word_url(sample_word)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SampleWord" do
        expect {
          post sample_words_url, params: { sample_word: valid_attributes }
        }.to change(SampleWord, :count).by(1)
      end

      it "redirects to the created sample_word" do
        post sample_words_url, params: { sample_word: valid_attributes }
        expect(response).to redirect_to(sample_word_url(SampleWord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SampleWord" do
        expect {
          post sample_words_url, params: { sample_word: invalid_attributes }
        }.to change(SampleWord, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sample_words_url, params: { sample_word: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sample_word" do
        sample_word = SampleWord.create! valid_attributes
        patch sample_word_url(sample_word), params: { sample_word: new_attributes }
        sample_word.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sample_word" do
        sample_word = SampleWord.create! valid_attributes
        patch sample_word_url(sample_word), params: { sample_word: new_attributes }
        sample_word.reload
        expect(response).to redirect_to(sample_word_url(sample_word))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        sample_word = SampleWord.create! valid_attributes
        patch sample_word_url(sample_word), params: { sample_word: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sample_word" do
      sample_word = SampleWord.create! valid_attributes
      expect {
        delete sample_word_url(sample_word)
      }.to change(SampleWord, :count).by(-1)
    end

    it "redirects to the sample_words list" do
      sample_word = SampleWord.create! valid_attributes
      delete sample_word_url(sample_word)
      expect(response).to redirect_to(sample_words_url)
    end
  end
end
