# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([ name: "Star Wars" ,  name: "Lord of the Rings" ])
#   Character.create(name: "Luke", movie: movies.first)
#NetballEducator.destroy_all
#NetballEducator.create(first_name: 'Jenna',last_name: 'Jones',email: 'jennajones88@gmail.com',phone: '1314555676',school_name: 'Hillview High School',city: 'Houston',state: 'TX', educator_notes: 'Callback for equipment', mgmt_notes: 'Spoke at meeting', );
#NetballEducator.create(first_name: 'Katlin',last_name: 'Smith',email: 'katlin99@gmail.com',phone: '1314888876',school_name: 'Valleyview High School',city: 'Dallas',state: 'TX', educator_notes: 'Callback for equipment', mgmt_notes: 'Spoke at meeting', );
#NetballEducator.create(first_name: 'Robin',last_name: 'Hall',email: 'robinhall@gmail.com',phone: '162345676',school_name: 'Jackson High School',city: 'Austin',state: 'TX', educator_notes: 'Callback for equipment', mgmt_notes: 'Spoke at session', );
Reference.destroy_all
Reference.create(group:	'sponsor_category',	value:	"Women's Products", active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'Oz companies', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'UK companies', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'NZ companies', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'Sth Africa companies', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'Caribbean companies', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'Pacific Islander companies', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Beverage', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Food', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Retail - Clothing', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Retail - Care Products', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Entertainment', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Financial Services', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Media', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Software', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Sports', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Telecommunications', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Tourism', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Transport', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Trade & Investment', active:	'TRUE');
Reference.create(group:	'sponsor_status',	value:	'Not Allocated', active:	'TRUE');
Reference.create(group:	'sponsor_status',	value:	'Not Started', active:	'TRUE');
Reference.create(group:	'sponsor_status',	value:	'In Progress', active:	'TRUE');
Reference.create(group:	'sponsor_status',	value:	'Completed', active:	'TRUE');
Reference.create(group:	'sponsor_opportunity_area',	value:	'Corporate', active:	'TRUE');
Reference.create(group:	'sponsor_opportunity_area',	value:	'BAI', active:	'TRUE');
Reference.create(group:	'sponsor_opportunity_area',	value:	'U.S. Open', active:	'TRUE');
Reference.create(group:	'sponsor_opportunity_area',	value:	'NNL', active:	'TRUE');
Reference.create(group:	'sponsor_opportunity_area',	value:	'Member', active:	'TRUE');
Reference.create(group:	'educator_level',	value:	'Elementary', active:	'TRUE');
Reference.create(group:	'educator_level',	value:	'Middle', active:	'TRUE');
Reference.create(group:	'educator_level',	value:	'High', active:	'TRUE');
Reference.create(group:	'educator_level',	value:	'University', active:	'TRUE');
Reference.create(group:	'educator_level',	value:	'School/District Lead', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'Not Started', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'In Progress', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'Completed', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'Submitted', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'Won', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'Lost', active:	'TRUE');
Reference.create(group:	'people_role',	value:	'Umpire', active:	'TRUE');
Reference.create(group:	'people_role',	value:	'Scorer', active:	'TRUE');
Reference.create(group:	'people_role',	value:	'Trainer', active:	'TRUE');
Reference.create(group:	'people_role',	value:	'Ambassador', active:	'TRUE');
Reference.create(group:	'people_region',	value:	'US & Canada', active:	'TRUE');
Reference.create(group:	'people_region',	value:	'International', active:	'TRUE');
Reference.create(group:	'people_level',	value:	'Beginner', active:	'TRUE');
Reference.create(group:	'people_level',	value:	'Intermediate', active:	'TRUE');
Reference.create(group:	'people_level',	value:	'Advanced', active:	'TRUE');
Reference.create(group:	'gender',	value:	'Female', active:	'TRUE');
Reference.create(group:	'gender',	value:	'Male', active:	'TRUE');
Reference.create(group:	'gender',	value:	'Other', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'XS', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'Small', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'Medium', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'Large', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'XL', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'XXL', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'XXXL', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'XXXXL', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Assessor/Mentor', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Int Umpire', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'US Umpire', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Scorer', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Operations', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Media', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'NA President', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Medic', active:	'TRUE');
Reference.create(group:	'transfer_room_type',	value:	'King', active:	'TRUE');
Reference.create(group:	'transfer_room_type',	value:	'Double Queen', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'Booth', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'Virtual Workshop', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'In Person Workshop', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'PE Class', active:	'TRUE');
Reference.create(group:	'event_status',	value:	'Plan', active:	'TRUE');
Reference.create(group:	'event_status',	value:	'Prep', active:	'TRUE');
Reference.create(group:	'event_status',	value:	'Complete', active:	'TRUE');
Reference.create(group:	'follow_up_lead_type',	value:	'Equipment', active:	'TRUE');
Reference.create(group:	'follow_up_lead_type',	value:	'Workshop', active:	'TRUE');
Reference.create(group:	'follow_up_lead_type',	value:	'Curriculum', active:	'TRUE');
Reference.create(group:	'follow_up_lead_type',	value:	'All', active:	'TRUE');
Reference.create(group:	'follow_up_status',	value:	'Not Allocated', active:	'TRUE');
Reference.create(group:	'follow_up_status',	value:	'Not Started', active:	'TRUE');
Reference.create(group:	'follow_up_status',	value:	'In Progress', active:	'TRUE');
Reference.create(group:	'follow_up_status',	value:	'Complete', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Pick-up by Chris', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Rental Car', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Media Rental Car', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Taxi/Uber to Hotel', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Pick-up by Steve', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Pick-up by Chris', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'In Rental Bus', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'In Rental Van', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'Taxi/Uber to Airport', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'Share Taxi/Uber to Airport', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'Drop off Rental Bus', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'Drop off Rental Van', active:	'TRUE');
Reference.create(group:	'us_open_hotel_name',	value:	'2023 - Marriott French Quarter', active:	'TRUE');
Reference.create(group:	'us_open_hotel_name',	value:	'2023- Best Western', active:	'TRUE');
Transfer.destroy_all
Transfer.create(first_name: 'Rebecca', last_name: 'Bole', role: 'Int Umpire', check_in: '04.11.2024', check_out: '07.11.2024', room_type: 'KING', hotel_reservation: 'CONFIRM: 349322 ', share_volunteer: 'RB 918208700 11/2', arrival_flight: 'BA225', arrival_time: '31.10.2024 14:35:00', no_pick_up: 'TRUE');
Transfer.create(first_name:'Lisa', last_name:'Benzie', role:'Int Umpire', check_in: '03.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349323', share_volunteer: 'Christine Tavers', arrival_flight: 'BA225', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Kodie', last_name:'Kuskopf', role:'Int Umpire', check_in: '01.11.2024', check_out: '06.11.2024', room_type: 'KING', hotel_reservation: 'CONFIRM: 349312', share_volunteer: 'Zara Margolis', arrival_flight: 'DL1387', arrival_time: '01.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Jane (Beth)', last_name:'Crump', role:'Int Umpire', check_in: '01.11.2024', check_out: '07.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349326. 1st November confirmation - 401655508. 5th 6th November confirmation - 441655603', share_volunteer: 'Aisha Kittimbo Nalumansi ', arrival_flight: 'DL2224', arrival_time: '01.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Deborah', last_name:'Edwards', role:'Assessor/Mentor', check_in: '01.11.2024', check_out: '07.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'marriott tues 10/31: 99473335 CONFIRM from 11.1: 349318', share_volunteer: 'Teresa Hames', arrival_flight: 'BA225', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Clare', last_name:'McCabe', role:'Assessor/Mentor', check_in: '01.11.2024', check_out: '06.11.2024', room_type: 'KING', hotel_reservation: 'CONFIRM: 349328', share_volunteer: '', arrival_flight: 'AA1007', arrival_time: '01.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Rachael', last_name:'Fletcher', role:'Int Umpire', check_in: '02.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349329', share_volunteer: 'Nina Bardowell', arrival_flight: 'VS4665', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Zoe', last_name:'Curtis', role:'Int Umpire', check_in: '02.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349365 FROM 11.2 to 11.6 ZC: 09962403 10/31 to 11/2.', share_volunteer: 'Joanna Sippets', arrival_flight: 'UA147', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Shaheen', last_name:'Lodhi', role:'Int Umpire', check_in: '02.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349330', share_volunteer: 'Sarah Lewis', arrival_flight: 'BA225', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Claire', last_name:'Legassick', role:'Int Umpire', check_in: '01.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349313', share_volunteer: 'Lisa Pethick', no_pick_up: 'FALSE');
Transfer.create(first_name:'Teresa', last_name:'Hames', role:'Int Umpire', check_in: '02.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349318', share_volunteer: 'Debbie Edwards', arrival_flight: 'VG1507', arrival_time: '02.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Lisa', last_name:'Pethick', role:'Operations', check_in: '01.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349313', share_volunteer: 'Claire Legassick', no_pick_up: 'FALSE');
Transfer.create(first_name:'Angela', last_name:'Ghavami', role:'Int Umpire', check_in: '04.11.2024', check_out:'07.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: '11.4 to 11.7 CONFIRM: 349317 ', share_volunteer: 'Pauline Jafarian', arrival_flight: 'BA225', arrival_time: '02.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Pauline', last_name:'Jafarian', role:'Scorer', check_in: '04.11.2024', check_out: '07.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349317', share_volunteer: 'Angela Ghavami', arrival_flight: 'BA225', arrival_time: '02.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Tracy', last_name:'Barnett', role:'Int Umpire', check_in: '02.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'Thurs 11.2 to Sun 11.5 CONFIRM: 349336 TB 419973406 Sun night.', share_volunteer: 'Karen Hill', arrival_flight: 'BA225', arrival_time: '02.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Kizzy', last_name:'Thomas', role:'Scorer', check_in: '03.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349306 2 nights', share_volunteer: 'Jacqueline Demmin', arrival_flight: 'BA1919', arrival_time: '03.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Nicole', last_name:'Clarkson', role:'Media', check_in: '02.11.2024', check_out: '05.11.2024', room_type: 'KING', hotel_reservation: 'Thursday night CONFIRM: 349310', share_volunteer: '', arrival_flight: 'AA2526', arrival_time: '02.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Nina', last_name:'Bardowell', role:'Int Umpire', check_in: '02.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM 11.2 - 11.5: 349329. Holiday Inn Express New Orleans Downtown, check in 31 Oct check out 2 Nov', share_volunteer: 'Rachael Fletcher', arrival_flight: 'VS4665', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Sarah', last_name:'Lewis', role:'Int Umpire', check_in: '02.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349330', share_volunteer: 'Shaheen Lodi', arrival_flight: 'BA225', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Karen', last_name:'Hill', role:'Int Umpire', check_in: '02.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349336', share_volunteer: 'Tracy Barnett', arrival_flight: 'BA225', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Jacqueline', last_name:'Demmin', role:'Scorer', check_in: '03.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349306 2 nights', share_volunteer: 'Kizzy Thomas', arrival_flight: 'AA2158', arrival_time: '03.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Lanika', last_name:'Ross', role:'Operations', check_in: '01.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349309', share_volunteer: 'Patricia', arrival_flight: 'DL2542', arrival_time: '01.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Patricia', last_name:'Ross', role:'Operations', check_in: '01.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349309', share_volunteer: 'Lanika', arrival_flight: 'DL2542', arrival_time: '01.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Natasha', last_name:'Ainsley-Thomas', role:'NA President', check_in: '01.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349305 5 nights', share_volunteer: 'Rachel', arrival_flight: 'BA225', arrival_time: '02.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Rachel', last_name:'Small', role:'NC', check_in: '03.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349305 2 nights only', share_volunteer: 'Natasha Ainsley-Thomas', arrival_flight: 'BA1919', arrival_time: '03.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Josh', last_name:'Eisenberg', role:'Media', check_in: '01.11.2024', check_out: '06.11.2024', room_type: 'KING', hotel_reservation: 'CONFIRM: 349303', share_volunteer: 'Josh Erin', arrival_flight: 'AA2526', arrival_time: '02.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Nick Vandevender', last_name:'Kin Kee Lui', role:'Media', check_in: '02.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349307', share_volunteer: 'Nick Kin', arrival_flight: 'VS4665', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Caprice', last_name:'Leonard', role:'Medic', check_in: '01.11.2024', check_out: '06.11.2024', room_type: 'KING', hotel_reservation: 'CONFIRM: 349308', share_volunteer: '', arrival_flight: 'BA225', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Antoinette', last_name:'Donaldson', role:'Scorer', check_in: '03.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349332', share_volunteer: 'Janet Cowan', arrival_flight: 'BA225', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Janet', last_name:'Cowan', role:'Scorer', check_in: '03.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349332', share_volunteer: 'Antoinette Donaldson', arrival_flight: 'AA2158', arrival_time: '03.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Lisa', last_name:'Edwards', role:'Scorer', check_in: '03.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349326', share_volunteer: 'Jane (Beth) Crump', arrival_flight: 'DL2542', arrival_time: '01.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Joanna', last_name:'Sippets', role:'Operations', check_in: '02.11.2024', check_out: '05.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349365', share_volunteer: 'Zoe Curtis (Umpire)', arrival_flight: 'DL2542', arrival_time: '01.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Hannah', last_name:'Otos', role:'Media', check_in: '02.11.2024', check_out: '06.11.2024', room_type: 'KING', hotel_reservation: 'CONFIRM: 349315', share_volunteer: '', arrival_flight: 'BA225', arrival_time: '31.10.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Alex', last_name:'Dodds', role:'Media', check_in: '02.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349331', share_volunteer: 'Simon Williams', arrival_flight: 'AA2158', arrival_time: '03.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Jacob', last_name:'Casey', role:'Media', check_in: '02.11.2024', check_out: '06.11.2024', room_type: 'KING', hotel_reservation: 'CONFIRM: 349334', share_volunteer: '', arrival_flight: 'DL2542', arrival_time: '01.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Michael', last_name:'Clubine', role:'Media', check_in: '02.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349615', share_volunteer: 'Danny Chin', arrival_flight: 'DL2542', arrival_time: '01.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Danny', last_name:'Chin', role:'Media', check_in: '02.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349615', share_volunteer: 'Michael Clubine', arrival_flight: 'UA2425', arrival_time: '02.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Rashid', last_name:'Muribu', role:'Int Umpire', check_in: '02.11.2024', check_out: '06.11.2024', room_type: 'DOUBLE QUEEN', hotel_reservation: 'CONFIRM: 349335', arrival_flight: 'UA2425', arrival_time: '02.11.2024', no_pick_up: 'TRUE');
Transfer.create(first_name:'Tim', last_name:'Taggart', role:'Operations', check_in: '03.11.2024', check_out: '04.11.2024', room_type: 'KING', hotel_reservation: 'CONFIRM: 349820', arrival_flight: 'AA2158', arrival_time: '03.11.2024', no_pick_up: 'TRUE');
