# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([ name: "Star Wars" ,  name: "Lord of the Rings" ])
#   Character.create(name: "Luke", movie: movies.first)
#NetballEducator.destroy_all
#NetballEducator.create(first_name: 'Jenna',last_name: 'Jones',email: 'jennajones88@gmail.com',phone: '1314555676',school_name: 'Hillview High School',city: 'Houston',state: 'TX', educator_notes: 'Callback for equipment', mgmt_notes: 'Spoke at meeting', );
#NetballEducator.create(first_name: 'Katlin',last_name: 'Smith',email: 'katlin99@gmail.com',phone: '1314888876',school_name: 'Valleyview High School',city: 'Dallas',state: 'TX', educator_notes: 'Callback for equipment', mgmt_notes: 'Spoke at meeting', );
#NetballEducator.create(first_name: 'Robin',last_name: 'Hall',email: 'robinhall@gmail.com',phone: '162345676',school_name: 'Jackson High School',city: 'Austin',state: 'TX', educator_notes: 'Callback for equipment', mgmt_notes: 'Spoke at session', );
Reference.destroy_all
Reference.create(group:	'sponsor_category',	value:	"Fitness", active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	"Teams", active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	"Theme Park", active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	"Airline", active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	"Women's Products", active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'Oz companies', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'UK companies', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'NZ companies', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'Sth Africa companies', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'Caribbean companies', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'Pacific Islander companies', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Beverage', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Entertainment', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Financial Services', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Food', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Health and Wellness', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Media', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Retail - Clothing', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Retail - Care Products', active:	'TRUE');
Reference.create(group:	'sponsor_category',	value:	'Software', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Sports', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Technology', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Telecommunications', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Tourism', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Transport', active:	'TRUE');
Reference.create(group:	'sponsor_industry',	value:	'Trade & Investment', active:	'TRUE');
Reference.create(group:	'sponsor_status',	value:	'Not Allocated', active:	'TRUE');
Reference.create(group:	'sponsor_status',	value:	'Not Started', active:	'TRUE');
Reference.create(group:	'sponsor_status',	value:	'In Progress', active:	'TRUE');
Reference.create(group:	'sponsor_status',	value:	'Completed', active:	'TRUE');
Reference.create(group:	'sponsor_type',	value:	'Cash', active:	'TRUE');
Reference.create(group:	'sponsor_type',	value:	'Product', active:	'TRUE');
Reference.create(group:	'sponsor_type',	value:	'Giftcard', active:	'TRUE');
Reference.create(group:	'sponsor_type',	value:	'Volunteer', active:	'TRUE');
Reference.create(group:	'sponsor_opportunity_area',	value:	'Corporate', active:	'TRUE');
Reference.create(group:	'sponsor_opportunity_area',	value:	'BAI', active:	'TRUE');
Reference.create(group:	'sponsor_opportunity_area',	value:	'U.S. Open', active:	'TRUE');
Reference.create(group:	'sponsor_opportunity_area',	value:	'NNL', active:	'TRUE');
Reference.create(group:	'sponsor_opportunity_area',	value:	'Member', active:	'TRUE');
Reference.create(group:	'educator_level',	value:	'Elementary', active:	'TRUE');
Reference.create(group:	'educator_level',	value:	'Middle', active:	'TRUE');
Reference.create(group:	'educator_level',	value:	'High', active:	'TRUE');
Reference.create(group:	'educator_level',	value:	'University', active:	'TRUE');
Reference.create(group:	'educator_level',	value:	'School/District Lead', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'Not Started', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'In Progress', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'Completed', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'Submitted', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'Won', active:	'TRUE');
Reference.create(group:	'grant_status',	value:	'Lost', active:	'TRUE');
Reference.create(group:	'people_role',	value:	'Umpire', active:	'TRUE');
Reference.create(group:	'people_role',	value:	'Scorer', active:	'TRUE');
Reference.create(group:	'people_role',	value:	'Trainer', active:	'TRUE');
Reference.create(group:	'people_role',	value:	'Coach', active:	'TRUE');
Reference.create(group:	'people_role',	value:	'Ambassador', active:	'TRUE');
Reference.create(group:	'people_role',	value:	'Operations', active:	'TRUE');
Reference.create(group:	'people_region',	value:	'US & Canada', active:	'TRUE');
Reference.create(group:	'people_region',	value:	'International', active:	'TRUE');
Reference.create(group:	'people_level',	value:	'New', active:	'TRUE');
Reference.create(group:	'people_level',	value:	'Beginner', active:	'TRUE');
Reference.create(group:	'people_level',	value:	'Intermediate', active:	'TRUE');
Reference.create(group:	'people_level',	value:	'Advanced', active:	'TRUE');
Reference.create(group:	'gender',	value:	'Female', active:	'TRUE');
Reference.create(group:	'gender',	value:	'Male', active:	'TRUE');
Reference.create(group:	'gender',	value:	'Other', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'XS', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'Small', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'Medium', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'Large', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'XL', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'2XL', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'3XL', active:	'TRUE');
Reference.create(group:	'tshirt_size',	value:	'4XL', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Assessor/Mentor', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Int Umpire', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'US Umpire', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Scorer', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Operations', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Media', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'NA President', active:	'TRUE');
Reference.create(group:	'us_open_role',	value:	'Medic', active:	'TRUE');
Reference.create(group:	'transfer_room_type',	value:	'King', active:	'TRUE');
Reference.create(group:	'transfer_room_type',	value:	'Double Queen', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'TBD', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'Booth', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'Virtual Workshop', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'In Person Workshop', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'PE Class', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'State Conference', active:	'TRUE');
Reference.create(group:	'event_type',	value:	'US Open', active:	'TRUE');
Reference.create(group:	'event_status',	value:	'Plan', active:	'TRUE');
Reference.create(group:	'event_status',	value:	'Prep', active:	'TRUE');
Reference.create(group:	'event_status',	value:	'Complete', active:	'TRUE');
Reference.create(group:	'follow_up_lead_type',	value:	'Equipment', active:	'TRUE');
Reference.create(group:	'follow_up_lead_type',	value:	'Workshop', active:	'TRUE');
Reference.create(group:	'follow_up_lead_type',	value:	'Curriculum', active:	'TRUE');
Reference.create(group:	'follow_up_lead_type',	value:	'All', active:	'TRUE');
Reference.create(group:	'follow_up_status',	value:	'Not Allocated', active:	'TRUE');
Reference.create(group:	'follow_up_status',	value:	'Not Started', active:	'TRUE');
Reference.create(group:	'follow_up_status',	value:	'In Progress', active:	'TRUE');
Reference.create(group:	'follow_up_status',	value:	'Complete', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Pick-up by Chris', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Rental Car', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Media Rental Car', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Taxi/Uber to Hotel', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Pick-up by Steve', active:	'TRUE');
Reference.create(group:	'transfer_pickup_type',	value:	'Pick-up by Chris', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'In Rental Bus', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'In Rental Van', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'Taxi/Uber to Airport', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'Share Taxi/Uber to Airport', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'Drop off Rental Bus', active:	'TRUE');
Reference.create(group:	'transfer_departure_type',	value:	'Drop off Rental Van', active:	'TRUE');
Reference.create(group:	'us_open_hotel_name',	value:	'2023 - Marriott French Quarter', active:	'FALSE');
Reference.create(group:	'us_open_hotel_name',	value:	'2023- Best Western', active:	'FALSE');
Reference.create(group:	'us_open_hotel_name',	value:	'2024 - DoubleTree Hotel by Hilton', desc: '#1 VIP and volunteers', active:	'TRUE');
Reference.create(group:	'us_open_hotel_name',	value:	'2024 - Courtyard by Marriott, Phoenix', desc: '#2', active:	'TRUE');
Reference.create(group:	'us_open_hotel_name',	value:	'2024 - Residence Inn by Marriott', desc: '#3',  active:	'TRUE');
Reference.create(group:	'transfer_hotel_arrival',	value:	'Thurs 7th Nov', active:	'TRUE');
Reference.create(group:	'transfer_hotel_arrival',	value:	'Frid 8th Nov', active:	'TRUE');
Reference.create(group:	'transfer_hotel_departure',	value:	'Sun 10th Nov', active:	'TRUE');
Reference.create(group:	'member_age_status',	value:	'Youth', active:	'TRUE');
Reference.create(group:	'member_age_status',	value:	'Adult', active:	'TRUE');
Reference.create(group:	'member_engagement_status',	value:	'Active', active:	'TRUE');
Reference.create(group:	'member_engagement_status',	value:	'Part-Time', active:	'TRUE');
Reference.create(group:	'member_membership_type',	value:	'Educator', active:	'TRUE');
Reference.create(group:	'member_membership_type',	value:	'Individual', active:	'TRUE');
Reference.create(group:	'member_membership_type',	value:	'Umpire', active:	'TRUE');
Reference.create(group:	'member_membership_type',	value:	'Coach', active:	'TRUE');
Reference.create(group:	'opportunity_outcome',	value:	'Pending Response', active:	'TRUE');
Reference.create(group:	'opportunity_outcome',	value:	'Win', active:	'TRUE');
Reference.create(group:	'opportunity_outcome',	value:	'Loss', active:	'TRUE');
Reference.create(group:	'opportunity_outcome',	value:	'No Response', active:	'TRUE');
Reference.create(group:	'member_positions',	value:	'Team President', active:	'TRUE');
Reference.create(group:	'member_positions',	value:	'Head Coach', active:	'TRUE');
Reference.create(group:	'member_positions',	value:	'Head Umpire', active:	'TRUE');
Reference.create(group:	'people_invite_back',	value:	'Yes', active:	'TRUE');
Reference.create(group:	'people_invite_back',	value:	'No', active:	'TRUE');
Reference.create(group:	'people_invite_back',	value:	'Conditional', active:	'TRUE');
Reference.create(group:	'timezones',	value:	'Eastern', active:	'TRUE');
Reference.create(group:	'timezones',	value:	'Central', active:	'TRUE');
Reference.create(group:	'timezones',	value:	'Mountain', active:	'TRUE');
Reference.create(group:	'timezones',	value:	'Pacific', active:	'TRUE');
Reference.create(group:	'timezones',	value:	'GMT', active:	'TRUE');
Reference.create(group:	'timezones',	value:	'Australian Eastern', active:	'TRUE');
Reference.create(group:	'timezones',	value:	'Australian Central', active:	'TRUE');
Reference.create(group:	'timezones',	value:	'Australian Western', active:	'TRUE');
Reference.create(group:	'regions',	value:	'North East', active:	'TRUE');
Reference.create(group:	'regions',	value:	'South East', active:	'TRUE');
Reference.create(group:	'regions',	value:	'South West', active:	'TRUE');
Reference.create(group:	'regions',	value:	'Mid West', active:	'TRUE');
Reference.create(group:	'regions',	value:	'West', active:	'TRUE');
Reference.create(group:	'regions',	value:	'Canada', active:	'TRUE');
Reference.create(group:	'regions',	value:	'Z - Unassigned', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Advanced Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Air Canada', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Air France', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Alaska Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Allegiant', active:	'TRUE');
Reference.create(group:	'airline',	value:	'American Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Breeze Airways', active:	'TRUE');
Reference.create(group:	'airline',	value:	'British Airways', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Condor Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Contour Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Delta Air Lines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Denver Air Connection', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Flair Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Frontier Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Hawaiian Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'JetBlue Airways', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Southern Airways Express', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Southwest Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Spirit Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Sun Country Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'United Airlines', active:	'TRUE');
Reference.create(group:	'airline',	value:	'Volaris', active:	'TRUE');
Reference.create(group:	'airline',	value:	'WestJet', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Alabama', key:	'AL', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Alaska', key:	'AK', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Arizona', key:	'AZ', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Arkansas', key:	'AR', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'California', key:	'CA', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Colorado', key:	'CO', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Connecticut', key:	'CT', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Delaware', key:	'DE', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'District of Columbia', key:	'DC', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Florida', key:	'FL', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Georgia', key:	'GA', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Hawaii', key:	'HI', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Idaho', key:	'ID', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Illinois', key:	'IL', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Indiana', key:	'IN', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Iowa', key:	'IA', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Kansas', key:	'KS', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Kentucky', key:	'KT', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Louisiana', key:	'LA', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Maine', key:	'ME', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Maryland', key:	'MD', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Massachusetts', key:	'MA', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Michigan', key:	'MI', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Minnesota', key:	'MN', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Mississippi', key:	'MS', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Missouri', key:	'MO', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Montana', key:	'MT', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Nebraska', key:	'NE', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Nevada', key:	'NV', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'New Hampshire', key:	'NH', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'New Jersey', key:	'NJ', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'New Mexico', key:	'NM', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'New York', key:	'NY', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'North Carolina', key:	'NC', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'North Dakota', key:	'ND', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Ohio', key:	'OH', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Oklahoma', key:	'OK', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Oregon', key:	'OR', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Pennsylvania', key:	'PA', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Puerto Rico', key:	'PR', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Rhode Island', key:	'RI', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'South Carolina', key:	'SC', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'South Dakota', key:	'SD', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Tennessee', key:	'TN', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Texas', key:	'TX', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Utah', key:	'UT', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Vermont', key:	'VT', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Virginia', key:	'VA', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Washington', key:	'WA', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'West Virginia', key:	'WV', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Wisconsin', key:	'WI', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Wyoming', key:	'WY', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'- CANADA - ', key:	'AB', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Alberta', key:	'AB', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'British Columbia', key:	'BC', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Manitoba', key:	'MB', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'New Brunswick', key:	'NB', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Newfoundland and Labrador', key:	'NL', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Northwest Territories', key:	'NT', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Nova Scotia', key:	'NS', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Nunavut', key:	'NU', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Ontario', key:	'ON', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Prince Edward Island', key:	'PE', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Quebec', key:	'QC', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Saskatchewan', key:	'SK', active:	'TRUE');
Reference.create(group:	'us_states',	value:	'Yukon', key:	'YK', active:	'TRUE');
Region.destroy_all
Region.create(state:'AL',	region:	'South East');
Region.create(state:'AK',	region:	'West');
Region.create(state:'AZ',	region:	'West');
Region.create(state:'AR',	region:	'South West');
Region.create(state:'CA',	region:	'West');
Region.create(state:'CO',	region:	'West');
Region.create(state:'CT',	region:	'North East');
Region.create(state:'DE',	region:	'North East');
Region.create(state:'DC',	region:	'North East');
Region.create(state:'FL',	region:	'South East');
Region.create(state:'GA',	region:	'South East');
Region.create(state:'GU',	region:	'Z - Unassigned');
Region.create(state:'HI',	region:	'West');
Region.create(state:'ID',	region:	'West');
Region.create(state:'IL',	region:	'Mid West');
Region.create(state:'IN',	region:	'Mid West');
Region.create(state:'IA',	region:	'Mid West');
Region.create(state:'KS',	region:	'South West');
Region.create(state:'KY',	region:	'Mid West');
Region.create(state:'LA',	region:	'South West');
Region.create(state:'ME',	region:	'North East');
Region.create(state:'MD',	region:	'North East');
Region.create(state:'MA',	region:	'North East');
Region.create(state:'MI',	region:	'Mid West');
Region.create(state:'MN',	region:	'Mid West');
Region.create(state:'MS',	region:	'South West');
Region.create(state:'MO',	region:	'Mid West');
Region.create(state:'MT',	region:	'Z - Unassigned');
Region.create(state:'NE',	region:	'Mid West');
Region.create(state:'NV',	region:	'Z - Unassigned');
Region.create(state:'NH',	region:	'North East');
Region.create(state:'NJ',	region:	'North East');
Region.create(state:'NM',	region:	'Z - Unassigned');
Region.create(state:'NY',	region:	'North East');
Region.create(state:'NC',	region:	'South East');
Region.create(state:'ND',	region:	'Mid West');
Region.create(state:'MP',	region:	'Z - Unassigned');
Region.create(state:'OH',	region:	'Mid West');
Region.create(state:'OK',	region:	'South West');
Region.create(state:'OR',	region:	'West');
Region.create(state:'PA',	region:	'North East');
Region.create(state:'PR',	region:	'Z - Unassigned');
Region.create(state:'RI',	region:	'North East');
Region.create(state:'SC',	region:	'South East');
Region.create(state:'SD',	region:	'Mid West');
Region.create(state:'TN',	region:	'South East');
Region.create(state:'TX',	region:	'South West');
Region.create(state:'UT',	region:	'West');
Region.create(state:'VT',	region:	'North East');
Region.create(state:'VA',	region:	'North East');
Region.create(state:'VI',	region:	'Z - Unassigned');
Region.create(state:'WA',	region:	'West');
Region.create(state:'WV',	region:	'North East');
Region.create(state:'WI',	region:	'Mid West');
Region.create(state:'WY',	region:	'Z - Unassigned');
Region.create(state:'AB',	region:	'West');
Region.create(state:'BC',	region:	'West');
Region.create(state:'MB',	region:	'Canada');
Region.create(state:'NB',	region:	'Canada');
Region.create(state:'NL',	region:	'Canada');
Region.create(state:'NT',	region:	'Canada');
Region.create(state:'NS',	region:	'Canada');
Region.create(state:'NU',	region:	'Canada');
Region.create(state:'ON',	region:	'Canada');
Region.create(state:'PE',	region:	'Canada');
Region.create(state:'QC',	region:	'Canada');
Region.create(state:'SK',	region:	'Canada');
Region.create(state:'YT',	region:	'Canada');